import part0 from './support-2.js';
import part1 from './support-3.js';
import part2 from './support-4.js';
import part3 from './support-5.js';
import part4 from './support-6.js';
import part5 from './support-7.js';
import part6 from './support-8.js';
import part7 from './support-9.js';
import part8 from './support-10.js';
import part9 from './support-11.js';
import part10 from './support-12.js';
import part11 from './support-13.js';
import part12 from './support-14.js';
export default {...part0, ...part1, ...part2, ...part3, ...part4, ...part5, ...part6, ...part7, ...part8, ...part9, ...part10, ...part11, ...part12};
