"""Deterministic brandkit finalization gauntlet.

Vendored from the sibling brandkit-agent repo (``brandkit_runtime`` @
6077f45): the validators/normalizers (``validation``), the final-brandkit
compose family with satellite loaders and the homepage-blocked gate
(``compose``), and the stale agent-authored artifact clearing (``stale``).

CLI: ``python <skill-root>/scripts/finalize.py`` (see ``__main__``).
"""

from .compose import (
    BRAND_VOICE_STOP_FILENAME,
    BUSINESS_CONTEXT_STOP_FILENAME,
    DEFAULT_BRAND_VOICE,
    DEFAULT_BUSINESS_CONTEXT,
    SATELLITE_STOP_FILES,
    HomepageBlockedError,
    HomepageStatusUnreadableError,
    SatelliteHardStopError,
    apply_standalone_satellites,
    collect_satellite_hard_stops,
    compose_final_brandkit,
    default_brand_voice,
    default_business_context,
    homepage_blocked_error,
    load_brand_voice,
    load_business_context,
    load_products,
    observed_asset_urls,
    resolve_homepage_gate,
    satellite_hard_stop_message,
)
from .stale import clear_stale_agent_authored_outputs
from .logo_hosting import (
    LogoHostingResult,
    SvgSidecarValidationError,
    ValidatedSvgSidecar,
    host_primary_logo,
    validate_svg_sidecar_for_upload,
)
from .validation import (
    HOMEPAGE_BLANK_RENDER_BLOCKER,
    HOMEPAGE_FAILED_WITHOUT_EVIDENCE_BLOCKER,
    HOMEPAGE_LANDED_DOCUMENT_ERROR_BLOCKER,
    TECHNICAL_HOMEPAGE_BLOCKED_BLOCKER,
    SchemaLoadError,
    SchemaPaths,
    SemanticValidationResult,
    TechnicalArtifactUnreadableError,
    detect_technical_artifact_blockers,
    homepage_status_failed_without_evidence,
    homepage_status_indicates_blocked,
    load_schema,
    normalize_extraction_stage_file,
    normalize_extraction_stage_payload,
    role_coverage_gap_warnings,
    role_coverage_gaps,
    stale_normalize_recovery_warnings,
    validate_brand_voice_payload,
    validate_brandkit_against_technical_artifacts,
    validate_brandkit_content,
    validate_brandkit_file,
    validate_brandkit_payload,
    validate_brandkit_semantics,
    validate_business_context_payload,
    validate_extraction_stage_file,
    validate_products_payload,
)

__all__ = [
    "BRAND_VOICE_STOP_FILENAME",
    "BUSINESS_CONTEXT_STOP_FILENAME",
    "DEFAULT_BRAND_VOICE",
    "DEFAULT_BUSINESS_CONTEXT",
    "HomepageBlockedError",
    "HOMEPAGE_BLANK_RENDER_BLOCKER",
    "HOMEPAGE_FAILED_WITHOUT_EVIDENCE_BLOCKER",
    "HOMEPAGE_LANDED_DOCUMENT_ERROR_BLOCKER",
    "HomepageStatusUnreadableError",
    "SATELLITE_STOP_FILES",
    "SatelliteHardStopError",
    "SchemaLoadError",
    "SchemaPaths",
    "SemanticValidationResult",
    "TECHNICAL_HOMEPAGE_BLOCKED_BLOCKER",
    "TechnicalArtifactUnreadableError",
    "apply_standalone_satellites",
    "clear_stale_agent_authored_outputs",
    "LogoHostingResult",
    "SvgSidecarValidationError",
    "ValidatedSvgSidecar",
    "host_primary_logo",
    "validate_svg_sidecar_for_upload",
    "collect_satellite_hard_stops",
    "compose_final_brandkit",
    "default_brand_voice",
    "default_business_context",
    "detect_technical_artifact_blockers",
    "homepage_blocked_error",
    "homepage_status_failed_without_evidence",
    "homepage_status_indicates_blocked",
    "load_brand_voice",
    "load_business_context",
    "load_products",
    "load_schema",
    "normalize_extraction_stage_file",
    "normalize_extraction_stage_payload",
    "observed_asset_urls",
    "resolve_homepage_gate",
    "role_coverage_gap_warnings",
    "role_coverage_gaps",
    "satellite_hard_stop_message",
    "stale_normalize_recovery_warnings",
    "validate_brand_voice_payload",
    "validate_brandkit_against_technical_artifacts",
    "validate_brandkit_content",
    "validate_brandkit_file",
    "validate_brandkit_payload",
    "validate_brandkit_semantics",
    "validate_business_context_payload",
    "validate_extraction_stage_file",
    "validate_products_payload",
]
